  version: '3.1'

  services:

    mysqldb:
      image: mysql:5.7
      container_name: mysqldb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: task
        MYSQL_DATABASE: task
      ports:
        - "3308:3306"

    php_and_app:
      build: .
      container_name: app
      ports:
        - "8001:8000"
      depends_on:
        - mysqldb
      links:
        - mysqldb



